### PR TITLE
[JENKINS-52724/JENKINS-52737] Inherit properties from the local docker config.json

### PR DESCRIPTION
**Pull request by kvalev**
When creating a new config folder, try to copy some of the properties of the existing config.json file.

Fixes [JENKINS-52724](https://issues.jenkins-ci.org/browse/JENKINS-52724) and [JENKINS-52737](https://issues.jenkins-ci.org/browse/JENKINS-52737).

### CODE REVIEW

**Comment by kvalev** [comment]
@jglick Can you please take a look at this PR.

**Comment by jglick** [comment]
Probably right? Did not look closely.

**Comment by jglick** [comment]
Amends #67 IIUC.

**Comment by oleg-nenashev** [comment]
@dwnusbaum did you have a chance to review it?

**Comment by dwnusbaum** [comment]
@oleg-nenashev No, the main patch seems fine at a glance but I'd want to look through Docker docs to understand what exactly can be in the file to see if anything else should be blacklisted before approving.

**Pull request merged**
