### PR TITLE
Do not require docker socket access in test

### PR DESCRIPTION
**Pull request by MarkEWaite**
## Do not require docker socket access in test

In order to include the docker-commons plugin in the plugin bill of materials, the tests need to pass on agents that do not have access to the docker socket.  One of the tests in the plugin assumed access to the docker socket, but did not do anything relevant with that access.

Remove the requirement for docker socket access from the test.

Also includes several other pull requests in the same request, since I think they should be included in the next release of the docker-commons plugin

- Bump authentication-tokens from 1.4 to 1.53.v1c90fd9191a_b_
- EOL JSR 305
- Bump plugin from 4.67 to 4.68
- Adapt test to not require docker socket access
- Use parent pom 4.70
- Use separate stream for stderr
- Use bom 2230.v0cb_4040cde55

If it will increase the chances of this being merged, I'm happy to provide a pull request that only makes the minimum changes necessary.  I wanted this larger set of changes so that the incremental build can be tested in the plugin BOM.

### Testing done

Automated tests confirmed to run as expected on Linux without docker socket access and Linux with docker socket access.

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by MarkEWaite** [comment]
@jglick I'd love to have the following pull requests merged before this pull request, with this one being labeled as a `developer` change:

* #131 
* #137 

The following pull request is no longer needed

* #128

**Comment by jglick** [comment]
Unfortunately this repo is not configured to allow merging of the base branch in the absence of conflicts, and I lack admin permission to enable that, so the diff will look larger than it really is.

**Comment by MarkEWaite** [comment]
> Unfortunately this repo is not configured to allow merging of the base branch in the absence of conflicts, and I lack admin permission to enable that, so the diff will look larger than it really is.

I'm happy to rework or replace the pull request with a much smaller diff if that will help the merge.

**Comment by MarkEWaite** [comment]
Thanks!

**Pull request merged**
