### PR TITLE
[JENKINS-28776] Fix broken icon.

### PR DESCRIPTION
**Pull request by KostyaSha**
@oleg-nenashev rtfm ;-)
https://github.com/jenkinsci/icon-shim-plugin/blob/master/icon-set/src/main/java/org/jenkins/ui/icon/IconSpec.java#L39

Verified manually with `hpi:run`

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
:+1:

**Comment by oleg-nenashev** [comment]
Requesting @reviewbybees (esp. @tfennelly )

**Comment by oleg-nenashev** [comment]
:bee: and @reviewbybees done
Maybe it was a cheat, but I want to release it

**Comment by stephenc** [comment]
@oleg-nenashev ok I'll remember this trick for next time I need it

**Pull request merged**
