### PR TITLE
remove check for default port! it should always set the port. This is…

### PR DESCRIPTION
**Pull request by ediri**
… important for private registries with tricky SSL Settings and Reverse Proxy Settings.

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
@jenkinsci/code-reviewers

**Comment by ediri** [comment]
no news here?

**Comment by ediri** [comment]
can someone approve this? @oleg-nenashev

**Comment by oleg-nenashev** [comment]
I suppose my vote is enough taking the fact there is no other responses

**Pull request merged**
