### PR TITLE
hide Docker installation option if no installation is defined

### PR DESCRIPTION
**Pull request by ndeloof**
For users (most of them imho) who will just rely on docker installation in default PATH

### CODE REVIEW

**Comment by ndeloof** [comment]
@reviewbybees

**Comment by oleg-nenashev** [comment]
:+1:

**Comment by oleg-nenashev** [comment]
Seems there's a merge conflict

**Comment by ndeloof** [comment]
I just rebased

**Comment by jtnord** [comment]
:+1:

**Comment by jglick** [comment]
:-1:, this contradicts [JENKINS-17373](https://issues.jenkins-ci.org/browse/JENKINS-17373) and I think it should be reverted.

**Comment by ndeloof** [comment]
@jesse proposed fix for JENKINS-17373 is the worst I can imagine : make the UI bad to prevent misconfigurations. Jenkins should just prevent to remove a ToolInstallation being used by some job and propose to rename them (as it does for job references).

**Comment by jglick** [comment]
> Jenkins should just prevent to remove a ToolInstallation being used by some job

Can try to do so in certain cases, but incompatible with code-as-config.

**Comment by ndeloof** [comment]
code as configuration would let you say "I need java 8" or "I need open JDK 8u45", then it's jenkins job to determine which ToolInstallation do match this vendor/version requirements. Relying on arbitrary display name is fragile and not portable across jenkins instances.

**Pull request merged**
