### PR TITLE
docker login - get password from stdin

### PR DESCRIPTION
**Pull request by jbiel**
This patch causes the `docker login` process to read the password from stdin rather than as an argument. Using an argument for the password causes issues with complex passwords (such as the JSON documents needed GCR) or passwords with special shell characters ($ especially.)

The `--password-stdin` flag was introduced in Docker version 17.07.0 so it's been around for a decent amount of time by now. The oldest supported version that doesn't have this flag (enterprise 17.06) is EOL on 2020-04-16, so perhaps this change could be merged in after that date.

This change will solve these open issues:

https://issues.jenkins-ci.org/browse/JENKINS-52761
https://issues.jenkins-ci.org/browse/JENKINS-53770

### CODE REVIEW

**Comment by jbiel** [comment]
Can this PR please be considered for merging? If there are any issues with it please let me know. Thanks!

**Comment by tschaible** [comment]
@rsandell @oleg-nenashev this PR looks complete and addresses some open issues (i found myself here after running into an issue with a password containing an $ today)

There are a few other PRs that look complete, but do not have further activity.

Is this plugin still maintained?  Has there been any discussion on potentially taking on more maintainers?

**Comment by oleg-nenashev** [comment]
More maintainers are always welcome! Personally I have difficulties with
maintaining all the things now:
https://twitter.com/oleg_nenashev/status/1376806410768498689?s=19

**Comment by tschaible** [comment]
Is there any guidance on how to be more involved and potentially be a maintainer.

I've read the Jenkins guidance for "Adopt a Plugin", but it says the following.

> First, make sure the plugin is not being actively maintained. Even in actively maintained plugins, there may be periods of lower developer activity. Don’t misinterpret failures to respond to questions or requests as the plugin being unmaintained!

That seems to apply to this plugin, so I'm just not sure how to get started in helping to move things forward.

**Comment by jbiel** [comment]
New plugin artifact based on this PR: https://ci.jenkins.io/job/Plugins/job/docker-commons-plugin/job/PR-86/5/artifact/org/jenkins-ci/plugins/docker-commons/1.19-rc360.265aa7b1edc3/docker-commons-1.19-rc360.265aa7b1edc3.hpi

**Comment by jbiel** [comment]
New build: https://ci.jenkins.io/job/Plugins/job/docker-commons-plugin/job/PR-86/7/artifact/org/jenkins-ci/plugins/docker-commons/1.20-rc369.ca0881662826/docker-commons-1.20-rc369.ca0881662826.hpi

**Comment by jbiel** [comment]
@rsandell - any chance you could please review this?

**Comment by mgar** [comment]
> New build: https://ci.jenkins.io/job/Plugins/job/docker-commons-plugin/job/PR-86/7/artifact/org/jenkins-ci/plugins/docker-commons/1.20-rc369.ca0881662826/docker-commons-1.20-rc369.ca0881662826.hpi

@jbiel – we are also experiencing the same issue, and I tried to update the plugin with that artifact, but now I'm getting the following error:

```
Cannot perform an interactive login from a non TTY device
```

Any idea?

**Review by rsandell — APPROVED** [review]

**Comment by moshavnik** [comment]
@mgar , @jbiel , we are also experiencing the same issue here while running withRegistry command inside a dind (docker in docker) container:
`Cannot perform an interactive login from a non TTY device`

**Comment by barney2k7** [comment]
This seems to break things for many people, see https://issues.jenkins.io/browse/JENKINS-69432 and https://issues.jenkins.io/browse/JENKINS-69436
@rsandell can this please be reverted and a new docker-commmons 1.21 published?

**Comment by nkalev** [comment]
This broke all of our builds, i would appreciate detailed usage description or a proper fix

**Comment by rsandell** [comment]
Reverted in v. 1.21

**Pull request merged**
