### PR TITLE
Configure findbugs xml output

### PR DESCRIPTION
**Pull request by rsandell**
So Jenkins can pick up the results

@reviewbybees

### CODE REVIEW

**Comment by recena** [comment]
:bee:

**Comment by stephenc** [comment]
:bee:

**Comment by aheritier** [comment]
:bee:

**Comment by oleg-nenashev** [comment]
@reviewbybees done

**Comment by stephenc** [comment]
@oleg-nenashev that was out of sequence...

**Comment by oleg-nenashev** [comment]
yes, sorry

**Pull request merged**
