### PR TITLE
Support Docker 1.7+ .docker/config.json

### PR DESCRIPTION
**Pull request by ndeloof**
Docker 1.7 introduced `.docker/config.json` which offer configuration extensibility. This file is preferred over `.dockercfg`, so if docker node has already ran some docker stuff with 1.7, jenkins just can't set credentials based on `.dockercfg`

### CODE REVIEW

**Comment by ndeloof** [comment]
@reviewbybees

**Comment by carlossg** [comment]
LGTM +1

**Comment by michaelneale** [comment]
:100:

**Comment by jglick** [comment]
BTW if https://github.com/docker/docker/pull/12856 and/or https://github.com/docker/docker/issues/10318 were addressed, the logic here could be improved (insofar as I understand those proposals).

**Comment by oleg-nenashev** [comment]
Caused https://issues.jenkins-ci.org/browse/JENKINS-29627, which has been fixed in docker-commons-1.2

**Pull request merged**
